language: java
jdk:
- oraclejdk8

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^spring-boot-frontend-maven-plugin-[0-9]+\.[0-9]+\.[0-9]+/
