language: java
jdk:
- oraclejdk8

before_install:
  - openssl aes-256-cbc -pass pass:${PASSPHRASE} -in secring.gpg.enc -out ~/.gnupg/secring.gpg -d
  - openssl aes-256-cbc -pass pass:${PASSPHRASE} -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:${PASSPHRASE} -in trustdb.gpg.enc -out ~/.gnupg/trustdb.gpg -d

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy -DskipTests=true -Dgpg.passphrase=${PASSPHRASE} -DperformRelease=true --settings travis-settings.xml

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^spring-boot-frontend-maven-plugin-[0-9]+\.[0-9]+\.[0-9]+/

env:
  global:
    - secure: "pBl1tSrfjxuAONJNfNsnzVm2Nd+njgt1VWUaAmpK8IgD4HJ1j6lN2Yosr5aopVEdI9H0ik/aibI0X2bpAX4K5Tdv+Y8wxj+DLmvCAIO3XOgMsy3JNuvJFxVbnrvqhXmEg4LoUr+fZASGJwaD6sCO85AKIncnKdmfeRF3Z94ASq7qY9rnJHKn/ldpfVZl9w6iBumR2QGaaB44GI/i0rflV4kxsBY+qCtMMpj61iRFMDXoIg+BjkpvOl6cC45f7RU9zrm+AY8fr5l9ify3P9Bq8zKMOB4AGS/2sO04JS6CYPjILAcqJRsvVOBDJWljQY6mB3SyQmfOdZf1ZFOyGdF2CoNqC/e3GFqNHIXiXMLz6q+Bz/wRA8lrk55uilauq4w+g5wzjwiRI3U9HNF7IMWC8Fp1j507rKARmOmK5V0Xkuh8C8kFiV4oi1BN1QwH9dNXAgzvC9wTRpJfIjHNoasbjURXrhJlz/rUjMqNURWNDCZrivEo0mcrTlLbYvvB1ILxJWAjK+QS1amO0xKMZ1YeNWqWulm05uT01eeLcI+GOm8/kkH39WZmPAlKhTXPJBuZBo/XtLFynnsIV2V/iI8fjjXagRtVOCURyO/6Cl183gKvyhWN9uFrAlTYd53SYRWUNC+qnjFGBPnZ6G99G5dnbrGV3djKd8VbTUEMKkXkfQg="
    - secure: "sjehSvZ4OhmEcveViDA3UQewhn3F6YndOdC/zT/+1QqyPVi7/lgKhcRw3bs/utOLmBHq38PtjGImtokYasL3lSXlIHkK9V4+8Wi/Tx+1/QlpTK8pjpwfWCe//VJcQ4N9D8SDjOVx9XPwFXEYR6tdcPVAkY5E5Ruq2Bn5QhnNwJQBiRHb5cjH0NgUD80p6qT3lwlC9zc48T7K0m/LMejDq2idcgM2NNTih/D+ugQ3sgj89gyrTc/j4CAsR7aNJSJ4ssnv5uYsZmrqMc+3pg/k7yp9LldfyAoK9hk8Hpo2GzQrnByXzT4ADuHg2u4NMhv27HkOiAiDnJKyS7BIEr0dNx3Plm/G41nBoIcVi3eRD/DFxCuxd+fiU9rfRoinZXk0JRHmnODPciLCMmbyTVxJzSXp0FNzOmNtk/h7O78qFDDssFKHsueCmhkRepNLlcRFnDfmLIKzKJ6ZRiPiJkGOSGHz6yIxvcxXgUXlHwky+d5QrPBM3fZdmcO99DhsQb4guZYKq0htGR0f8xOd3Y7YaxCbIicy/4uhVtkOtaYb5oMnCgya5oTUrfdLHTJVVhibMlceUo/1xRVDx1zfnuaUodITwc8C0YtPGUDWVLz8qDaGI7svnJVzeGVDIljukc9WdNAjeMSWhYmC0zz/Ebmw3zlpglMqCu2g3b9mvRnbaBs="
    - secure: "axCct2SZnOpwrj7Z901HGQznw0hU+J0Qb32A30rZPLO+IMnFGPPdW6wJ2EsZZ+zoUjizXUrD31TmO6fgIZ8PV7pANWWUsg/hnVu9+W95us1O2ORZj3E533iHVwy3y4BtQghLm5QbNELMCwf5oSrlRBE5mlwMdf2rVUdYQrYbF5Qc4zpmmSCMOu8VA1znJtiIUkxmGkNOdy2GRmHvmoZLPD5lcpR3y/KDjeDVxMSGs9oPSmMKUsW+1dFVSCdnAZ8MK+uWDc/3GdslaCFdFHbWx1i5u9q37DD0zS1EspdjQ95Ofu+tj+mcf6zzDz1G2PiD/S0nW6sktGZN+dCM9AJFl9QjF15OJb607U00Mbf5tAq8DxjzpPnHnhf+3sKrCHWCg6u2vx3vrq2E3E2XmihRQEMgsGk6JeCkjcYPcUrVJ87W+chTWnMn8Ergr2oKUqqS09s0xo4OlGTkKxJfmtX6fFaEEbWZH+n7ef3tscxTBBGL3O0rqVCT8KdOBSDqtoqBgQ+MnmcnpJubnwlD74lH+/HzYYfs7qOrbLJPYhUUCIH309UFqiPHloExX2eT8PwVvrg8yNyMh+JacfeIMJSrNk5AZMDQTrcrSsGckGZdnXitMie4oDVBS9qR+dGS6S11dlyUWEvr8+4C5+KH4Eng6ZHQrZ6pJGmi+nWA6sMoHfQ="


